model_config:
  encoder_layers:
    - { out_channels: 8, kernel_size: 3, stride: 1, padding: 1 }
    - { out_channels: 16, kernel_size: 3, stride: 1, padding: 1 }
    - { out_channels: 32, kernel_size: 3, stride: 3, padding: 1 }
    - { out_channels: 32, kernel_size: 3, stride: 1, padding: 1 }
    - { out_channels: 32, kernel_size: 3, stride: 1, padding: 1 }
    - { out_channels: 8, kernel_size: 1, stride: 1, padding: 0 }
  latent_dim: 1000
  input_channels: 3
  input_size: [250, 250]

training_config:
  learning_rate: 0.001
  batch_size: 400
  epochs: 50
  dropout: 0.1
